# Generated by Django 6.0.4 on 2026-04-20 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_photos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
